-- +goose Up
CREATE TABLE CHIRPS (
  ID UUID PRIMARY KEY,
  CREATED_AT TIMESTAMP NOT NULL,
  UPDATED_AT TIMESTAMP NOT NULL,
  BODY TEXT NOT NULL,
  USER_ID UUID NOT NULL,
  CONSTRAINT FK_USER 
  FOREIGN KEY (USER_ID)
  REFERENCES USERS(ID)
  ON DELETE CASCADE 
);

-- +goose Down
DROP TABLE CHIRPS;