-- +goose Up
CREATE TABLE REFRESH_TOKEN (
  TOKEN TEXT PRIMARY KEY,
  CREATED_AT DATE NOT NULL,
  UPDATED_AT DATE NOT NULL,
  USER_ID UUID NOT NULL,
  EXPIRES_AT DATE NOT NULL,
  REVOKED_AT DATE,
  CONSTRAINT FK_USERS 
  FOREIGN KEY (USER_ID)
  REFERENCES USERS(ID)
);

-- +goose Down
DROP TABLE REFRESH_TOKEN;